name: Deploy Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: mkdir .public && mv * .public && mv .public public
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        id: deployment
        with:
          path: public/

      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
